import Link from 'next/link';

export default function Home() {
  return <>
    <section className="hero"><div className="hero-copy"><span className="eyebrow">FÉ QUE SE TRANSFORMA EM CUIDADO</span><h1>Juntos, a gente<br/>faz o bem <em>acontecer.</em></h1><p>Somos os Mensageiros da Cruz Tupã. Um grupo de jovens que vive o Evangelho no encontro, na amizade e no serviço à comunidade.</p><div className="button-row"><a className="button button-orange" href="#participar">Quero conhecer o grupo <span aria-hidden="true">↗</span></a><Link className="text-link" href="/previa">Explorar o projeto →</Link></div><div className="hero-note"><span aria-hidden="true">✦</span> Juventude, fé e solidariedade em Tupã.</div></div>
      <div className="hero-art" role="img" aria-label="Ilustração abstrata de caminhos que se encontram em torno de uma cruz"><div className="art-grid"/><div className="art-circle circle-one"/><div className="art-circle circle-two"/><div className="art-cross">✚</div><div className="art-caption"><span>UMA MESMA FÉ.</span><strong>Muitas formas<br/>de fazer o bem.</strong></div><span className="art-star" aria-hidden="true">✳</span></div>
    </section>
    <section id="sobre" className="section"><div className="section-heading"><div><span className="eyebrow">QUEM SOMOS</span><h2>Uma comunidade.<br/>Um propósito compartilhado.</h2></div><p>Na Paróquia São Pedro Apóstolo, cultivamos a vivência do Evangelho e a participação dos jovens na comunidade. Cada encontro é uma oportunidade de aprender, acolher e colaborar.</p></div><div className="values-grid"><article className="value-card"><span className="card-number">01 / ENCONTRAR</span><h3>A fé nos aproxima.</h3><p>Encontros, convivência e formação para caminhar juntos e fortalecer os vínculos.</p></article><article className="value-card"><span className="card-number">02 / ACOLHER</span><h3>A presença faz diferença.</h3><p>Visitas e ações de solidariedade, com escuta e cuidado com as pessoas da comunidade.</p></article><article className="value-card"><span className="card-number">03 / COLABORAR</span><h3>Cada gesto tem seu lugar.</h3><p>Participação nas atividades paroquiais e apoio à organização de ações, como as quermesses.</p></article></div></section>
    <section className="project-section"><div><span className="eyebrow">JUVENTUDE EM AÇÃO</span><h2>Mais clareza para<br/>cuidar de cada ação.</h2><p>Estamos construindo um espaço para reunir a agenda, organizar tarefas e acompanhar os materiais de cada atividade do grupo.</p><Link className="button" href="/previa">Experimentar a prévia <span aria-hidden="true">→</span></Link></div><div className="project-list"><div><span>01</span><p><strong>Encontre a próxima ação</strong>Data, local e orientações em um só lugar.</p></div><div><span>02</span><p><strong>Escolha como participar</strong>Confirme seu interesse e assuma uma tarefa.</p></div><div><span>03</span><p><strong>Acompanhe sua contribuição</strong>Ofertas e materiais recebidos, cada um com seu estado.</p></div><small>A prévia usa exemplos fictícios. A área real é exclusiva para pessoas convidadas.</small></div></section>
    <section id="participar" className="section join-section"><span className="eyebrow">VAMOS CAMINHAR JUNTOS</span><h2>Seu próximo passo<br/>pode ser um encontro.</h2><p>Para conhecer o grupo, procure a coordenação dos Mensageiros da Cruz Tupã na Paróquia São Pedro Apóstolo.</p><p><a className="text-link" href="https://www.instagram.com/mensageirosdacruz_tupa/" target="_blank" rel="noopener noreferrer">Acompanhe o grupo no Instagram @mensageirosdacruz_tupa ↗</a></p><p className="muted">Confirme os horários dos encontros com a coordenação.</p><Link className="text-link" href="/entrar">Já recebeu um convite? Acesse a área do grupo →</Link></section>
  </>;
}
